Repository alamin-karno/flutter-crisp-chat, pull requests merged in 2024-12, with the labels that each got.

#25 feat: notification feature
  README.md
  android/build.gradle
  example/android/app/build.gradle
  example/android/app/src/main/AndroidManifest.xml
  example/android/settings.gradle
  example/lib/main.dart
  example/pubspec.yaml
  ios/Classes/SwiftFlutterCrispChatPlugin.swift
Labels: enhancement

#26 feat(docs): update files for new release
  CHANGELOG.md
  README.md
  ios/crisp_chat.podspec
  pubspec.yaml
Labels: documentation

#30 chore(changelog): add proper hyperlink to issues
  CHANGELOG.md
Labels: documentation

#31 docs(readme): add manifest configuration to resolve metadata conflict
  README.md
Labels: documentation

#32 fix: resolve conflict in `application:didFinishLaunchingWithOptions:` method for `UIApplicationDelegate` conformance
  ios/Classes/SwiftFlutterCrispChatPlugin.swift
Labels: bug

#34 fix: Resolve conflict with `application:didFinishLaunchingWithOptions:` in Flutter lifecycle
  ios/Classes/SwiftFlutterCrispChatPlugin.swift
Labels: bug

#37 fix: crisp ios sdk version not specified
  example/ios/Podfile
  ios/Classes/SwiftFlutterCrispChatPlugin.swift
  ios/crisp_chat.podspec
Labels: enhancement
